DROP DATABASE IF EXISTS pms_prototype;
CREATE DATABASE pms_prototype CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pms_prototype;

CREATE TABLE projects (
  id INT PRIMARY KEY AUTO_INCREMENT,
  project_code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  contract_no VARCHAR(100),
  project_type ENUM('COLD_STORAGE', 'BUILDING', 'DOOR', 'MATERIAL') NOT NULL,
  business_type ENUM('MATERIAL', 'INSTALLATION', 'EPC') NOT NULL DEFAULT 'EPC',
  customer_name VARCHAR(255) NOT NULL,
  division_name VARCHAR(100) NOT NULL,
  project_manager VARCHAR(100) NOT NULL,
  status ENUM('PLANNING', 'IN_PROGRESS', 'DELAYED', 'ACCEPTANCE', 'WARRANTY', 'CLOSED') NOT NULL DEFAULT 'PLANNING',
  start_date DATE,
  planned_end_date DATE,
  shipped_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  collected_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  contract_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE project_documents (
  id INT PRIMARY KEY AUTO_INCREMENT,
  project_id INT NOT NULL,
  doc_type ENUM('CONTRACT', 'SAFETY_DISCLOSURE', 'ACCEPTANCE_FORM', 'INVOICE', 'DRAWING', 'OTHER') NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  uploaded_by VARCHAR(100),
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_required TINYINT(1) NOT NULL DEFAULT 0,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE contracts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  project_id INT NOT NULL,
  contract_code VARCHAR(60) NOT NULL UNIQUE,
  contract_type ENUM('SALES', 'PROCUREMENT', 'LABOR', 'CHANGE') NOT NULL,
  contract_name VARCHAR(255) NOT NULL,
  counterparty_name VARCHAR(255) NOT NULL,
  amount DECIMAL(14,2) NOT NULL,
  tax_rate DECIMAL(5,2) NOT NULL DEFAULT 13.00,
  payment_terms VARCHAR(255),
  signed_date DATE,
  status ENUM('DRAFT', 'APPROVED', 'EXECUTING', 'COMPLETED', 'CHANGED') NOT NULL DEFAULT 'APPROVED',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE cost_entries (
  id INT PRIMARY KEY AUTO_INCREMENT,
  project_id INT NOT NULL,
  contract_id INT NULL,
  version_type ENUM('SIGNED', 'BUDGET', 'ACTUAL') NOT NULL,
  cost_category ENUM('MAIN_MATERIAL', 'AUX_MATERIAL', 'LABOR', 'EXPENSE', 'SHIPPING', 'OTHER') NOT NULL,
  amount DECIMAL(14,2) NOT NULL,
  entry_date DATE NOT NULL,
  source_ref VARCHAR(100),
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE SET NULL
);

CREATE TABLE remaining_materials (
  id INT PRIMARY KEY AUTO_INCREMENT,
  project_id INT NOT NULL,
  material_name VARCHAR(255) NOT NULL,
  specification VARCHAR(255),
  quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
  unit VARCHAR(50) NOT NULL DEFAULT 'pcs',
  estimated_value DECIMAL(14,2) NOT NULL DEFAULT 0,
  status ENUM('REUSABLE', 'TO_BE_SCRAPPED', 'SOLD', 'REDEPLOYED') NOT NULL DEFAULT 'REUSABLE',
  disposal_notes TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE finance_transactions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  project_id INT NOT NULL,
  contract_id INT NULL,
  transaction_type ENUM('COLLECTION_PLAN', 'COLLECTION', 'PAYMENT_PLAN', 'PAYMENT_REQUEST', 'REIMBURSEMENT', 'WAGE_DISBURSEMENT', 'PREPAYMENT') NOT NULL,
  direction ENUM('INCOME', 'EXPENSE') NOT NULL,
  amount DECIMAL(14,2) NOT NULL,
  due_date DATE NULL,
  transaction_date DATE NULL,
  status ENUM('PLANNED', 'PENDING', 'APPROVED', 'PAID', 'BLOCKED', 'OVERDUE') NOT NULL DEFAULT 'PLANNED',
  vendor_name VARCHAR(255),
  applicant VARCHAR(100),
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE SET NULL
);

CREATE TABLE budget_adjustments (
  id INT PRIMARY KEY AUTO_INCREMENT,
  project_id INT NOT NULL,
  request_type ENUM('PAYMENT', 'REIMBURSEMENT') NOT NULL,
  requested_amount DECIMAL(14,2) NOT NULL,
  budget_amount DECIMAL(14,2) NOT NULL,
  actual_expense_amount DECIMAL(14,2) NOT NULL,
  status ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  reason TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE site_records (
  id INT PRIMARY KEY AUTO_INCREMENT,
  project_id INT NOT NULL,
  record_type ENUM('PROCUREMENT', 'SHIPPING', 'MATERIAL', 'LABOR', 'SAFETY', 'ACCEPTANCE') NOT NULL,
  title VARCHAR(255) NOT NULL,
  vendor_or_team VARCHAR(255),
  status ENUM('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', 'PENDING_CONFIRM') NOT NULL DEFAULT 'PLANNING',
  planned_date DATE NULL,
  actual_date DATE NULL,
  amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
  unit VARCHAR(50),
  details TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

